import { Text, VStack, HStack, Section, Spacer } from '@expo/ui/swift-ui';
import {
  font,
  foregroundStyle,
  frame,
  cornerRadius,
  padding,
  background,
  lineLimit,
} from '@expo/ui/swift-ui/modifiers';
import { createWidget, type WidgetEnvironment } from 'expo-widgets';

/**
 * Props passed to the widget from the configurable timeline provider.
 * The native AppIntent selects a bookshelf and passes its data here.
 *
 * NOTE: The actual widget rendering is handled by the native Swift code
 * generated by plugins/withConfigurableWidget.js, which overrides this TSX.
 * This file is kept in sync for documentation / preview purposes.
 */
type BookshelfWidgetProps = {
  isPremium: boolean;
  bookshelfName: string | null;
  bookshelfId: string | null;
  coverColor: string | null;
  shelfStyle: 'full' | 'bottom';
  books: {
    id: string;
    title: string;
    author: string;
    imageUrl: string | null;
    resolvedImageUrl: string | null;
  }[];
};

/**
 * Generates a stable hue from a string (same algorithm as the Swift widget).
 */
function stableHue(title: string): string {
  let hash = 0;
  for (let i = 0; i < title.length; i++) {
    hash += title.charCodeAt(i);
  }
  const hue = (hash % 360);
  return `hsl(${hue}, 50%, 55%)`;
}

/** Mirrors adjustHexBrightness in utils/shelfColors.ts. */
function adjustHexBrightness(color: string, amount: number): string {
  const channels = [1, 3, 5].map((index) => {
    const value = parseInt(color.slice(index, index + 2), 16);
    return Math.min(255, Math.max(0, Math.round(value + amount)));
  });
  return `#${channels.map((v) => v.toString(16).padStart(2, '0')).join('')}`;
}

/**
 * Shelf palette derived from the bookshelf cover color — mirrors
 * getShelfColors in utils/shelfColors.ts (and the ShelfPalette port in the
 * native Swift widget). The native widget renders the frame/plank as
 * top-to-bottom gradients; this preview uses the gradient top colors.
 */
function getWidgetShelfPalette(coverColor: string | null) {
  const DEFAULT_SHELF_COLOR = '#7a4f2c'; // Wood.plankTop
  const hex =
    coverColor && /^#[0-9a-fA-F]{6}$/.test(coverColor.trim())
      ? coverColor.trim()
      : DEFAULT_SHELF_COLOR;

  if (hex.toLowerCase() === DEFAULT_SHELF_COLOR) {
    return {
      frame: '#8a5a30', // Wood.frameTop
      frameEdge: '#b98a52', // Wood.frameEdge
      plank: '#7a4f2c', // Wood.plankTop
      back: '#e9dcc2', // Wood.backTop
    };
  }

  return {
    frame: adjustHexBrightness(hex, 18),
    frameEdge: adjustHexBrightness(hex, 56),
    plank: adjustHexBrightness(hex, 8),
    // Back panel is a slightly darker shade of the shelf color, matching
    // getShelfColors' backGradient top color
    back: adjustHexBrightness(hex, -44),
  };
}

function seededNormalized(bookId: string, title: string, salt: string): number {
  const source = `${bookId}-${title}-${salt}`;
  let hash = 0;

  for (let i = 0; i < source.length; i += 1) {
    hash = source.charCodeAt(i) + ((hash << 5) - hash);
  }

  return Math.abs(hash % 1000) / 1000;
}

function imageHeightFactor(bookId: string, title: string): number {
  const min = 0.8;
  const max = 0.95;
  return min + seededNormalized(bookId, title, 'image-height') * (max - min);
}

/**
 * Returns the max number of book spines to consider for a given widget
 * family. Rows are filled by actual spine width (see splitIntoRows), so
 * this is only an upper bound. Medium = 1 row, Large = 2 rows.
 */
function maxBooksForFamily(family: string): number {
  switch (family) {
    case 'systemMedium':
      return 15;
    default:
      return 30;
  }
}

/** A book paired with its computed spine display size. */
type SpineData = {
  book: BookshelfWidgetProps['books'][number];
  width: number;
  height: number;
};

/**
 * Distributes spines across shelf rows by their actual widths: spines stay
 * on the current row until the next one no longer fits, and only then start
 * filling the next row — so a book is only bumped to the second shelf when
 * the first shelf is full. Spines that don't fit on the last row are
 * dropped. Always returns exactly rowCount rows (possibly empty).
 */
function splitIntoRows(
  spines: SpineData[],
  rowContentWidth: number,
  rowCount: number
): SpineData[][] {
  const rows: SpineData[][] = Array.from({ length: rowCount }, () => []);
  let rowIndex = 0;
  let usedWidth = 0;

  for (const spine of spines) {
    if (usedWidth + spine.width > rowContentWidth && rows[rowIndex].length > 0) {
      rowIndex += 1;
      usedWidth = 0;
      if (rowIndex >= rowCount) break;
    }
    rows[rowIndex].push(spine);
    usedWidth += spine.width;
  }

  return rows;
}

/**
 * Renders a single row of book spines with shelf background.
 */
function SpineRow({
  spines: spineData,
  shelfBackColor,
  shelfColor,
  shelfStyle,
}: {
  spines: SpineData[];
  shelfBackColor: string;
  shelfColor: string;
  shelfStyle: 'full' | 'bottom';
}) {
  /*
   * NOTE: matching the in-app BookSpine, the native widget clips every spine
   * (image or placeholder) with rounded corners (3pt top / 1pt bottom) and
   * casts a warm shadow onto the plank; placeholder spines also get the
   * horizontal cloth sheen gradient. This preview approximates that with a
   * uniform corner radius.
   */
  const spines = spineData.map(({ book, width, height }) => (
    <Section key={book.id}>
      <VStack
        modifiers={[
          frame({ width, height }),
          cornerRadius(3),
          background(stableHue(book.title)),
        ]}
      >
        <Text
          modifiers={[
            font({ weight: 'bold', size: Math.round(width * 0.38) }),
            foregroundStyle('#FFFFFF'),
          ]}
        >
          {book.title.charAt(0)}
        </Text>
      </VStack>
    </Section>
  ));

  /*
   * NOTE: matching the in-app bookshelf, spines are laid out with zero
   * spacing and bottom alignment so adjacent spines touch and every spine
   * rests on the shelf ledge. The native Swift widget additionally derives
   * each spine's width from its image's natural aspect ratio (clamped, and
   * scaled down proportionally if a row would overflow) so images fill
   * their frames exactly with no letterboxing gaps.
   */
  return (
    <VStack>
      {shelfStyle === 'bottom' ? (
        /* Bottom line shelf: no background, just spines */
        <HStack
          spacing={0}
          alignment="bottom"
          modifiers={[
            padding({ horizontal: 4 }),
          ]}
        >
          {spines}
        </HStack>
      ) : (
        /* Full shelf: spines on the warm lit back panel, inside the cabinet
           frame (the native widget draws the back panel and frame as
           top-to-bottom gradients). No plank: books rest on the cabinet
           frame strip below the row. */
        <HStack
          spacing={0}
          alignment="bottom"
          modifiers={[
            background(shelfBackColor),
            padding({ horizontal: 12 }),
          ]}
        >
          {spines}
        </HStack>
      )}

      {/* Shelf ledge — only for the open 'bottom' style, where the plank is
          the shelf itself */}
      {shelfStyle === 'bottom' && (
        <VStack
          modifiers={[
            frame({ height: 12 }),
            background(shelfColor),
          ]}
        >
          {/* The ledge is a bare colored plank; Spacer gives the stack the
              child SwiftUI requires without drawing anything itself. */}
          <Spacer />
        </VStack>
      )}
    </VStack>
  );
}

/**
 * BookshelfWidget component rendered using @expo/ui SwiftUI primitives.
 * Medium: single shelf row with bookshelf title.
 * Large: two shelf rows with bookshelf title.
 *
 * Each row displays spine images (or colored placeholders) on a shelf
 * background with the bookshelf's cover color.
 */
const BookshelfWidget = (
  props: BookshelfWidgetProps,
  environment: WidgetEnvironment
) => {
  'widget';

  const { isPremium, bookshelfName, bookshelfId, coverColor, shelfStyle, books } = props;
  const family = environment.widgetFamily;
  const maxBooks = maxBooksForFamily(family);
  const visibleBooks = books.slice(0, maxBooks);

  // The native widget now fills the whole widget edge to edge (no outer
  // margin, system content margins disabled), so spines and the cabinet
  // frame are proportionally larger than before.
  const spineWidth = 44;
  const spineHeight = family === 'systemMedium' ? 130 : 154;
  // Shelf colors derived from the bookshelf cover color, matching the
  // in-app cabinet (utils/shelfColors.ts)
  const palette = getWidgetShelfPalette(coverColor);
  const shelfColor = palette.plank;
  const shelfBackColor = palette.back;

  // Subscription gate: show upgrade prompt for free users
  if (!isPremium) {
    return (
      <VStack modifiers={[padding({ all: 12 })]}>
        <Text
          modifiers={[
            font({ weight: 'semibold', size: 14 }),
            foregroundStyle('#8E8E93'),
          ]}
        >
          Subscribe to display your shelf
        </Text>
      </VStack>
    );
  }

  // Empty state when no bookshelf is selected
  if (!bookshelfName || !bookshelfId) {
    return (
      <VStack modifiers={[padding({ all: 12 })]}>
        <Text
          modifiers={[
            font({ size: 13 }),
            foregroundStyle('#8E8E93'),
          ]}
        >
          Long-press to choose a shelf
        </Text>
      </VStack>
    );
  }

  const isLarge = family === 'systemLarge';

  // Rows fill by actual spine width, not a fixed count: a book is only
  // bumped to the second shelf once the first shelf has no room left.
  // The native Swift widget measures the real row width with GeometryReader;
  // this preview uses a fixed estimate of the widget's usable width.
  const estimatedRowContentWidth = 305;
  const spineData: SpineData[] = visibleBooks.map((book) => {
    const scale = imageHeightFactor(book.id, book.title);
    return {
      book,
      width: Math.max(18, Math.round(spineWidth * scale)),
      height: Math.round(spineHeight * scale),
    };
  });
  const [topRow, bottomRow] = splitIntoRows(
    spineData,
    estimatedRowContentWidth,
    isLarge ? 2 : 1
  );

  return (
    <VStack
      modifiers={[
        padding({ all: 0 }),
        background('#fbf6ec'),
      ]}
    >
      {/* Cabinet: wood frame around all rows (full style only), matching
          the in-app EditableBookshelfGrid cabinet. It fills the entire
          widget — in the native widget it's clipped to the widget's own
          rounded shape (ContainerRelativeShape) and stroked with a 1px
          lighter frame edge. */}
      <VStack
        modifiers={
          shelfStyle === 'full'
            ? [padding({ bottom: 12 }), background(palette.frame), cornerRadius(12)]
            : []
        }
      >
        {/* First row of spines with shelf */}
        <SpineRow
          spines={topRow}
          shelfBackColor={shelfBackColor}
          shelfColor={shelfColor}
          shelfStyle={shelfStyle}
        />

        {/* Second row of spines with shelf (large only) */}
        {isLarge && bottomRow.length > 0 && (
          <SpineRow
            spines={bottomRow}
            shelfBackColor={shelfBackColor}
            shelfColor={shelfColor}
            shelfStyle={shelfStyle}
          />
        )}
      </VStack>
    </VStack>
  );
};

export default createWidget('BookshelfWidget', BookshelfWidget);
