import { Text, VStack, HStack, Section } from '@expo/ui/swift-ui';
import {
  font,
  foregroundStyle,
  frame,
  cornerRadius,
  padding,
  background,
  lineLimit,
} from '@expo/ui/swift-ui/modifiers';
import { createWidget, type WidgetEnvironment } from 'expo-widgets';

/**
 * Props passed to the widget from the configurable timeline provider.
 * The native AppIntent selects a bookshelf and passes its data here.
 *
 * NOTE: The actual widget rendering is handled by the native Swift code
 * generated by plugins/withConfigurableWidget.js, which overrides this TSX.
 * This file is kept in sync for documentation / preview purposes.
 */
type BookshelfWidgetProps = {
  isPremium: boolean;
  bookshelfName: string | null;
  bookshelfId: string | null;
  coverColor: string | null;
  shelfStyle: 'full' | 'bottom';
  books: {
    id: string;
    title: string;
    author: string;
    imageUrl: string | null;
    resolvedImageUrl: string | null;
  }[];
};

/**
 * Generates a stable hue from a string (same algorithm as the Swift widget).
 */
function stableHue(title: string): string {
  let hash = 0;
  for (let i = 0; i < title.length; i++) {
    hash += title.charCodeAt(i);
  }
  const hue = (hash % 360);
  return `hsl(${hue}, 50%, 55%)`;
}

function seededNormalized(bookId: string, title: string, salt: string): number {
  const source = `${bookId}-${title}-${salt}`;
  let hash = 0;

  for (let i = 0; i < source.length; i += 1) {
    hash = source.charCodeAt(i) + ((hash << 5) - hash);
  }

  return Math.abs(hash % 1000) / 1000;
}

function imageHeightFactor(bookId: string, title: string): number {
  const min = 0.8;
  const max = 0.95;
  return min + seededNormalized(bookId, title, 'image-height') * (max - min);
}

/**
 * Returns the max number of book spines to show for a given widget family.
 * Medium = 1 row (7 books), Large = 2 rows (14 books).
 */
function maxBooksForFamily(family: string): number {
  switch (family) {
    case 'systemMedium':
      return 7;
    default:
      return 14;
  }
}

/**
 * Renders a single row of book spines with shelf background.
 */
function SpineRow({
  books,
  spineWidth,
  spineHeight,
  shelfBackColor,
  shelfColor,
  shelfStyle,
}: {
  books: BookshelfWidgetProps['books'];
  spineWidth: number;
  spineHeight: number;
  shelfBackColor: string;
  shelfColor: string;
  shelfStyle: 'full' | 'bottom';
}) {
  const spines = books.map((book) => {
    const scale = imageHeightFactor(book.id, book.title);
    const scaledHeight = Math.round(spineHeight * scale);
    const scaledWidth = Math.max(18, Math.round(spineWidth * scale));

    return (
    <Section key={book.id}>
      <VStack
        modifiers={[
          frame({ width: scaledWidth, height: scaledHeight }),
          cornerRadius(1),
          background(stableHue(book.title)),
        ]}
      >
        <Text
          modifiers={[
            font({ weight: 'bold', size: Math.round(scaledWidth * 0.38) }),
            foregroundStyle('#FFFFFF'),
          ]}
        >
          {book.title.charAt(0)}
        </Text>
      </VStack>
    </Section>
    );
  });

  /*
   * NOTE: matching the in-app bookshelf, spines are laid out with zero
   * spacing and bottom alignment so adjacent spines touch and every spine
   * rests on the shelf ledge. The native Swift widget additionally derives
   * each spine's width from its image's natural aspect ratio (clamped, and
   * scaled down proportionally if a row would overflow) so images fill
   * their frames exactly with no letterboxing gaps.
   */
  return (
    <VStack>
      {shelfStyle === 'bottom' ? (
        /* Bottom line shelf: no background, just spines */
        <HStack
          spacing={0}
          alignment="bottom"
          modifiers={[
            padding({ horizontal: 3 }),
          ]}
        >
          {spines}
        </HStack>
      ) : (
        /* Full shelf: spines on a background with uniform border */
        <HStack
          spacing={0}
          alignment="bottom"
          modifiers={[
            background(shelfBackColor),
            cornerRadius(2),
            padding({ horizontal: 8 }),
          ]}
        >
          {spines}
        </HStack>
      )}

      {/* Shelf ledge */}
      <VStack
        modifiers={[
          frame({ height: 8 }),
          background(shelfColor),
        ]}
      />
    </VStack>
  );
}

/**
 * BookshelfWidget component rendered using @expo/ui SwiftUI primitives.
 * Medium: single shelf row with bookshelf title.
 * Large: two shelf rows with bookshelf title.
 *
 * Each row displays spine images (or colored placeholders) on a shelf
 * background with the bookshelf's cover color.
 */
const BookshelfWidget = (
  props: BookshelfWidgetProps,
  environment: WidgetEnvironment
) => {
  'widget';

  const { isPremium, bookshelfName, bookshelfId, coverColor, shelfStyle, books } = props;
  const family = environment.widgetFamily;
  const maxBooks = maxBooksForFamily(family);
  const visibleBooks = books.slice(0, maxBooks);

  const spineWidth = 36;
  const spineHeight = family === 'systemMedium' ? 108 : 124;
  const shelfColor = coverColor || '#8B4513';
  const shelfBackColor = '#654321';

  // Subscription gate: show upgrade prompt for free users
  if (!isPremium) {
    return (
      <VStack modifiers={[padding({ all: 12 })]}>
        <Text
          modifiers={[
            font({ weight: 'semibold', size: 14 }),
            foregroundStyle('#8E8E93'),
          ]}
        >
          Subscribe to display your shelf
        </Text>
      </VStack>
    );
  }

  // Empty state when no bookshelf is selected
  if (!bookshelfName || !bookshelfId) {
    return (
      <VStack modifiers={[padding({ all: 12 })]}>
        <Text
          modifiers={[
            font({ size: 13 }),
            foregroundStyle('#8E8E93'),
          ]}
        >
          Long-press to choose a shelf
        </Text>
      </VStack>
    );
  }

  const isLarge = family === 'systemLarge';
  const booksPerRow = 7;
  const topRow = visibleBooks.slice(0, booksPerRow);
  const bottomRow = isLarge ? visibleBooks.slice(booksPerRow, booksPerRow * 2) : [];

  return (
    <VStack
      modifiers={[
        padding({ all: 0 }),
        background('#fbf6ec'),
      ]}
    >
      {/* First row of spines with shelf */}
      <SpineRow
        books={topRow}
        spineWidth={spineWidth}
        spineHeight={spineHeight}
        shelfBackColor={shelfBackColor}
        shelfColor={shelfColor}
        shelfStyle={shelfStyle}
      />

      {/* Second row of spines with shelf (large only) */}
      {isLarge && bottomRow.length > 0 && (
        <SpineRow
          books={bottomRow}
          spineWidth={spineWidth}
          spineHeight={spineHeight}
          shelfBackColor={shelfBackColor}
          shelfColor={shelfColor}
          shelfStyle={shelfStyle}
        />
      )}
    </VStack>
  );
};

export default createWidget('BookshelfWidget', BookshelfWidget);
