import { Text, VStack, HStack, Section } from '@expo/ui/swift-ui';
import {
  font,
  foregroundStyle,
  frame,
  cornerRadius,
  padding,
  background,
  lineLimit,
} from '@expo/ui/swift-ui/modifiers';
import { createWidget, type WidgetEnvironment } from 'expo-widgets';

/**
 * Props passed to the widget from the configurable timeline provider.
 * The native AppIntent selects a bookshelf and passes its data here.
 *
 * NOTE: The actual widget rendering is handled by the native Swift code
 * generated by plugins/withConfigurableWidget.js, which overrides this TSX.
 * This file is kept in sync for documentation / preview purposes.
 */
type BookshelfWidgetProps = {
  isPremium: boolean;
  bookshelfName: string | null;
  bookshelfId: string | null;
  coverColor: string | null;
  shelfStyle: 'full' | 'bottom';
  books: {
    id: string;
    title: string;
    author: string;
    imageUrl: string | null;
    resolvedImageUrl: string | null;
  }[];
};

/**
 * Generates a stable hue from a string (same algorithm as the Swift widget).
 */
function stableHue(title: string): string {
  let hash = 0;
  for (let i = 0; i < title.length; i++) {
    hash += title.charCodeAt(i);
  }
  const hue = (hash % 360);
  return `hsl(${hue}, 50%, 55%)`;
}

function seededNormalized(bookId: string, title: string, salt: string): number {
  const source = `${bookId}-${title}-${salt}`;
  let hash = 0;

  for (let i = 0; i < source.length; i += 1) {
    hash = source.charCodeAt(i) + ((hash << 5) - hash);
  }

  return Math.abs(hash % 1000) / 1000;
}

function imageHeightFactor(bookId: string, title: string): number {
  const min = 0.8;
  const max = 0.95;
  return min + seededNormalized(bookId, title, 'image-height') * (max - min);
}

/**
 * Returns the max number of book spines to consider for a given widget
 * family. Rows are filled by actual spine width (see splitIntoRows), so
 * this is only an upper bound. Medium = 1 row, Large = 2 rows.
 */
function maxBooksForFamily(family: string): number {
  switch (family) {
    case 'systemMedium':
      return 15;
    default:
      return 30;
  }
}

/** A book paired with its computed spine display size. */
type SpineData = {
  book: BookshelfWidgetProps['books'][number];
  width: number;
  height: number;
};

/**
 * Distributes spines across shelf rows by their actual widths: spines stay
 * on the current row until the next one no longer fits, and only then start
 * filling the next row — so a book is only bumped to the second shelf when
 * the first shelf is full. Spines that don't fit on the last row are
 * dropped. Always returns exactly rowCount rows (possibly empty).
 */
function splitIntoRows(
  spines: SpineData[],
  rowContentWidth: number,
  rowCount: number
): SpineData[][] {
  const rows: SpineData[][] = Array.from({ length: rowCount }, () => []);
  let rowIndex = 0;
  let usedWidth = 0;

  for (const spine of spines) {
    if (usedWidth + spine.width > rowContentWidth && rows[rowIndex].length > 0) {
      rowIndex += 1;
      usedWidth = 0;
      if (rowIndex >= rowCount) break;
    }
    rows[rowIndex].push(spine);
    usedWidth += spine.width;
  }

  return rows;
}

/**
 * Renders a single row of book spines with shelf background.
 */
function SpineRow({
  spines: spineData,
  shelfBackColor,
  shelfColor,
  shelfStyle,
}: {
  spines: SpineData[];
  shelfBackColor: string;
  shelfColor: string;
  shelfStyle: 'full' | 'bottom';
}) {
  const spines = spineData.map(({ book, width, height }) => (
    <Section key={book.id}>
      <VStack
        modifiers={[
          frame({ width, height }),
          cornerRadius(1),
          background(stableHue(book.title)),
        ]}
      >
        <Text
          modifiers={[
            font({ weight: 'bold', size: Math.round(width * 0.38) }),
            foregroundStyle('#FFFFFF'),
          ]}
        >
          {book.title.charAt(0)}
        </Text>
      </VStack>
    </Section>
  ));

  /*
   * NOTE: matching the in-app bookshelf, spines are laid out with zero
   * spacing and bottom alignment so adjacent spines touch and every spine
   * rests on the shelf ledge. The native Swift widget additionally derives
   * each spine's width from its image's natural aspect ratio (clamped, and
   * scaled down proportionally if a row would overflow) so images fill
   * their frames exactly with no letterboxing gaps.
   */
  return (
    <VStack>
      {shelfStyle === 'bottom' ? (
        /* Bottom line shelf: no background, just spines */
        <HStack
          spacing={0}
          alignment="bottom"
          modifiers={[
            padding({ horizontal: 3 }),
          ]}
        >
          {spines}
        </HStack>
      ) : (
        /* Full shelf: spines on a background with uniform border */
        <HStack
          spacing={0}
          alignment="bottom"
          modifiers={[
            background(shelfBackColor),
            cornerRadius(2),
            padding({ horizontal: 8 }),
          ]}
        >
          {spines}
        </HStack>
      )}

      {/* Shelf ledge */}
      <VStack
        modifiers={[
          frame({ height: 8 }),
          background(shelfColor),
        ]}
      />
    </VStack>
  );
}

/**
 * BookshelfWidget component rendered using @expo/ui SwiftUI primitives.
 * Medium: single shelf row with bookshelf title.
 * Large: two shelf rows with bookshelf title.
 *
 * Each row displays spine images (or colored placeholders) on a shelf
 * background with the bookshelf's cover color.
 */
const BookshelfWidget = (
  props: BookshelfWidgetProps,
  environment: WidgetEnvironment
) => {
  'widget';

  const { isPremium, bookshelfName, bookshelfId, coverColor, shelfStyle, books } = props;
  const family = environment.widgetFamily;
  const maxBooks = maxBooksForFamily(family);
  const visibleBooks = books.slice(0, maxBooks);

  const spineWidth = 36;
  const spineHeight = family === 'systemMedium' ? 108 : 124;
  const shelfColor = coverColor || '#8B4513';
  const shelfBackColor = '#654321';

  // Subscription gate: show upgrade prompt for free users
  if (!isPremium) {
    return (
      <VStack modifiers={[padding({ all: 12 })]}>
        <Text
          modifiers={[
            font({ weight: 'semibold', size: 14 }),
            foregroundStyle('#8E8E93'),
          ]}
        >
          Subscribe to display your shelf
        </Text>
      </VStack>
    );
  }

  // Empty state when no bookshelf is selected
  if (!bookshelfName || !bookshelfId) {
    return (
      <VStack modifiers={[padding({ all: 12 })]}>
        <Text
          modifiers={[
            font({ size: 13 }),
            foregroundStyle('#8E8E93'),
          ]}
        >
          Long-press to choose a shelf
        </Text>
      </VStack>
    );
  }

  const isLarge = family === 'systemLarge';

  // Rows fill by actual spine width, not a fixed count: a book is only
  // bumped to the second shelf once the first shelf has no room left.
  // The native Swift widget measures the real row width with GeometryReader;
  // this preview uses a fixed estimate of the widget's usable width.
  const estimatedRowContentWidth = 300;
  const spineData: SpineData[] = visibleBooks.map((book) => {
    const scale = imageHeightFactor(book.id, book.title);
    return {
      book,
      width: Math.max(18, Math.round(spineWidth * scale)),
      height: Math.round(spineHeight * scale),
    };
  });
  const [topRow, bottomRow] = splitIntoRows(
    spineData,
    estimatedRowContentWidth,
    isLarge ? 2 : 1
  );

  return (
    <VStack
      modifiers={[
        padding({ all: 0 }),
        background('#fbf6ec'),
      ]}
    >
      {/* First row of spines with shelf */}
      <SpineRow
        spines={topRow}
        shelfBackColor={shelfBackColor}
        shelfColor={shelfColor}
        shelfStyle={shelfStyle}
      />

      {/* Second row of spines with shelf (large only) */}
      {isLarge && bottomRow.length > 0 && (
        <SpineRow
          spines={bottomRow}
          shelfBackColor={shelfBackColor}
          shelfColor={shelfColor}
          shelfStyle={shelfStyle}
        />
      )}
    </VStack>
  );
};

export default createWidget('BookshelfWidget', BookshelfWidget);
