-- Migration: Switch to anonymous authentication
-- Removes the email column from the users table and updates
-- RLS policies so anonymous Supabase auth users can access their own data.

-- Step 1: Make name nullable (generated by trigger but must accept NULL as fallback)
ALTER TABLE users ALTER COLUMN name DROP NOT NULL;

-- Step 2: Drop the email column entirely (anonymous-only app; no email needed)
ALTER TABLE users DROP COLUMN IF EXISTS email;

-- Step 3: Enable anonymous sign-in in auth config
-- NOTE: Anonymous sign-in must also be enabled in the Supabase Dashboard:
-- Authentication > Providers > Anonymous Sign-Ins > Enable
-- This migration handles the database-side changes only.

-- Step 4: Ensure RLS policies on the users table allow anonymous auth users
-- to access their own row. Since anonymous users still get a valid auth.uid(),
-- the existing policies (which check user_id = auth.uid()) remain correct.
-- We just need to make sure the users table has appropriate policies.

-- Drop existing users policies to recreate cleanly
DO $$
DECLARE
  pol RECORD;
BEGIN
  FOR pol IN
    SELECT policyname
    FROM pg_policies
    WHERE tablename = 'users' AND schemaname = 'public'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON users', pol.policyname);
  END LOOP;
END;
$$;

-- Ensure RLS is enabled
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- Users can read their own profile
CREATE POLICY "Users can read own profile"
  ON users FOR SELECT
  USING (id = auth.uid());

-- Users can insert their own profile (needed for anonymous sign-up)
CREATE POLICY "Users can insert own profile"
  ON users FOR INSERT
  WITH CHECK (id = auth.uid());

-- Users can update their own profile
CREATE POLICY "Users can update own profile"
  ON users FOR UPDATE
  USING (id = auth.uid());

-- Allow reading other users' names for community features
CREATE POLICY "Anyone can read user names"
  ON users FOR SELECT
  USING (true);
